### ISSUE TITLE
Receiving 'invalid byte sequence in US-ASCII' error

### ISSUE THREAD

**Issue by matthewgovaere** [yevgenko/cookbook-php-fpm#36]
When trying to run on an Ubuntu 14.04 (Trusty) box, I get this error below.

Specific box: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-i386-vagrant-disk1.box

It does work fine on a Precise box.

```
[2014-04-27T19:21:37+00:00] INFO: service[nginx] reloaded
[2014-04-27T19:21:37+00:00] INFO: template[/etc/php5/fpm/php-fpm.conf] sending restart action to service[php-fpm] (delayed)
[2014-04-27T19:21:37+00:00] ERROR: Running exception handlers
[2014-04-27T19:21:37+00:00] ERROR: Exception handlers complete
[2014-04-27T19:21:37+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2014-04-27T19:21:37+00:00] ERROR: Chef::Exceptions::MultipleFailures

================================================================================
Error executing action `restart` on resource 'service[php-fpm]'
================================================================================


ArgumentError
-------------
invalid byte sequence in US-ASCII


Resource Declaration:
---------------------
# In /tmp/vagrant-chef-2/chef-solo-1/cookbooks/php-fpm/recipes/default.rb

114: service "php-fpm" do
115:   provider service_provider if service_provider
116:   service_name php_fpm_service_name
117:   supports :start => true, :stop => true, :restart => true, :reload => true
118:   action [ :enable, :start ]
119: end
120: 



Compiled Resource:
------------------
# Declared in /tmp/vagrant-chef-2/chef-solo-1/cookbooks/php-fpm/recipes/default.rb:114:in `from_file'

service("php-fpm") do
  provider Chef::Provider::Service::Upstart
  action [:enable, :start]
  supports {:start=>true, :stop=>true, :restart=>true, :reload=>true}
  retries 0
  retry_delay 2
  service_name "php5-fpm"
  pattern "php-fpm"
  startup_type :automatic
  cookbook_name :"php-fpm"
  recipe_name "default"
end



[2014-04-27T19:17:34+00:00] INFO: Forking chef instance to converge...
[2014-04-27T19:21:38+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Basic run list...

```
run_list(
    "recipe[nginx]",
    "recipe[php]",
    "recipe[php-fpm]"
)
```

**Comment by vineetmadan** [comment]
I'm facing a similar error. I'm using Opscode managed chef and my node is a Ubuntu 14.04 EC2.  I'm getting error "invalid byte sequence in UTF-8" in mysql server recipe that is modified to use password from a data bag. It's a simple recipe to install mysql:

-------------------------------------------------------------------------------------------
ArgumentError
-------------
invalid byte sequence in UTF-8

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/lamp/recipes/mysql.rb:1:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/lamp/recipes/mysql.rb:

  1>> mysqlpass = Chef::EncryptedDataBagItem.load("mysql", "rtpass")
  2:
  3:  mysql_service "mysqldefault" do
  4:    initial_root_password mysqlpass["password"]
  5:    action [:create, :start]
  6:  end  7:
d
----------------------------------------------------------------------------------------------------

What do i have to do to get this past this?

**Comment by lamont-granquist** [comment]
You need to upgrade your chef-client version to 12.x, this issue is closed (and i'm unsubscribing to it now)

**Comment by vineetmadan** [comment]
I'm already running a chef-client version 12.5.1.

**Comment by nirav-chotai** [comment]
@vineetmadan  opening the secret_key file and saving as UTF-8 fixes the problem
