### ISSUE TITLE
Missing Metadata.rb on Chef Supermarket

### ISSUE THREAD

**Issue by pknath19** [yevgenko/cookbook-php-fpm#61]
Cookbook php-fpm version 0.7.0 successfully installed
ERROR: IOError: Cannot open or read /home/chefclient/chef-repo/cookbooks/php-fpm/metadata.rb!

Download missing metadata.rb http://cookbooks.opscode.com/cookbooks/php-fpm/download
Re-release with stove to get a metadata.rb
Fix: Re-release with stove 3.2.2 to get a metadata.rb

**Comment by vwxyz** [comment]
>ERROR: IOError: Cannot open or read /home/chefclient/chef-repo/cookbooks/php-fpm/metadata.rb!

You need to use chef  v12.02 or later

chef/chef#2345

Only `metadata.json` is supported

**Comment by yevgenko** [comment]
Thank you @vwxyz  :+1:
